// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VideoMessenger.Models;

namespace VideoMessenger.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("VideoMessenger.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ChatName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ChatName = "RI-390003",
                            CreationDate = new DateTime(2021, 12, 16, 13, 16, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = -2,
                            ChatName = "Gamers Room",
                            CreationDate = new DateTime(2021, 12, 2, 20, 16, 11, 191, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("VideoMessenger.Models.ChatInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RecipientId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatInvitations");
                });

            modelBuilder.Entity("VideoMessenger.Models.ChatParticipant", b =>
                {
                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("ChatId", "UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatParticipants");

                    b.HasData(
                        new
                        {
                            ChatId = -1,
                            UserId = -1,
                            RoleId = 1
                        },
                        new
                        {
                            ChatId = -1,
                            UserId = -2,
                            RoleId = 2
                        },
                        new
                        {
                            ChatId = -1,
                            UserId = -3,
                            RoleId = 3
                        },
                        new
                        {
                            ChatId = -2,
                            UserId = -2,
                            RoleId = 1
                        },
                        new
                        {
                            ChatId = -2,
                            UserId = -1,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("VideoMessenger.Models.FriendInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RecipientId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("FriendInvitations");
                });

            modelBuilder.Entity("VideoMessenger.Models.Friends", b =>
                {
                    b.Property<int>("FriendId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FriendId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Friends");

                    b.HasData(
                        new
                        {
                            FriendId = -2,
                            UserId = -1
                        },
                        new
                        {
                            FriendId = -1,
                            UserId = -2
                        },
                        new
                        {
                            FriendId = -3,
                            UserId = -1
                        },
                        new
                        {
                            FriendId = -1,
                            UserId = -3
                        });
                });

            modelBuilder.Entity("VideoMessenger.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<bool>("IsReaded")
                        .HasColumnType("boolean");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ChatId = -1,
                            CreationDate = new DateTime(2021, 12, 16, 13, 16, 10, 191, DateTimeKind.Local),
                            Data = "Привет, как у вас дела?",
                            IsReaded = true,
                            SenderId = -1
                        },
                        new
                        {
                            Id = -2,
                            ChatId = -1,
                            CreationDate = new DateTime(2021, 12, 16, 13, 16, 12, 191, DateTimeKind.Local),
                            Data = "Привет, нормально",
                            IsReaded = true,
                            SenderId = -2
                        },
                        new
                        {
                            Id = -3,
                            ChatId = -1,
                            CreationDate = new DateTime(2021, 12, 16, 13, 16, 14, 191, DateTimeKind.Local),
                            Data = "Отлично! Как у тебя?",
                            IsReaded = true,
                            SenderId = -3
                        },
                        new
                        {
                            Id = -4,
                            ChatId = -1,
                            CreationDate = new DateTime(2021, 12, 16, 13, 16, 16, 191, DateTimeKind.Local),
                            Data = "Могло быть и лучше",
                            IsReaded = true,
                            SenderId = -1
                        },
                        new
                        {
                            Id = -5,
                            ChatId = -1,
                            CreationDate = new DateTime(2021, 12, 16, 13, 16, 20, 191, DateTimeKind.Local),
                            Data = "Что случилось?",
                            IsReaded = true,
                            SenderId = -2
                        },
                        new
                        {
                            Id = -6,
                            ChatId = -1,
                            CreationDate = new DateTime(2021, 12, 16, 13, 16, 25, 191, DateTimeKind.Local),
                            Data = "Получил 4 по алгебре",
                            IsReaded = true,
                            SenderId = -1
                        },
                        new
                        {
                            Id = -7,
                            ChatId = -1,
                            CreationDate = new DateTime(2021, 12, 16, 13, 16, 30, 191, DateTimeKind.Local),
                            Data = "У меня вообще тройка, не стоит отчаиваться",
                            IsReaded = true,
                            SenderId = -3
                        },
                        new
                        {
                            Id = -8,
                            ChatId = -1,
                            CreationDate = new DateTime(2021, 12, 16, 13, 16, 35, 191, DateTimeKind.Local),
                            Data = "Нормально все будет",
                            IsReaded = true,
                            SenderId = -2
                        },
                        new
                        {
                            Id = -9,
                            ChatId = -1,
                            CreationDate = new DateTime(2021, 12, 16, 13, 16, 36, 191, DateTimeKind.Local),
                            Data = "Приезжайте ко мне, будем в шашки играть",
                            IsReaded = true,
                            SenderId = -3
                        },
                        new
                        {
                            Id = -10,
                            ChatId = -1,
                            CreationDate = new DateTime(2021, 12, 16, 13, 16, 38, 191, DateTimeKind.Local),
                            Data = "Выезжаю...",
                            IsReaded = false,
                            SenderId = -1
                        },
                        new
                        {
                            Id = -11,
                            ChatId = -2,
                            CreationDate = new DateTime(2021, 12, 2, 20, 16, 11, 191, DateTimeKind.Local),
                            Data = "Good bye, World!",
                            IsReaded = true,
                            SenderId = -2
                        },
                        new
                        {
                            Id = -12,
                            ChatId = -2,
                            CreationDate = new DateTime(2021, 12, 2, 21, 16, 11, 191, DateTimeKind.Local),
                            Data = "My life be like, uuuuaaaa",
                            IsReaded = false,
                            SenderId = -3
                        });
                });

            modelBuilder.Entity("VideoMessenger.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "creator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "moderator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "user"
                        });
                });

            modelBuilder.Entity("VideoMessenger.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            EmailAddress = "vasya322@ya.ru",
                            Login = "Pupok",
                            Password = "$2a$11$aM0vfoLUHEqor6PfJZuiruGpPWtaWz3Q9lu1yja20fYme4A.1gIZ6",
                            PhoneNumber = "+78222345678",
                            Username = "Vasya"
                        },
                        new
                        {
                            Id = -2,
                            EmailAddress = "igor2005@ya.ru",
                            Login = "Uxo",
                            Password = "$2a$11$g5CtJNIfcaPEdaMtYU1Kb.JD8UrjOJu3S.9cEIsCC4TdAVxFffNHi",
                            PhoneNumber = "+79221234564",
                            Username = "Igor"
                        },
                        new
                        {
                            Id = -3,
                            EmailAddress = "sodeep@ya.ru",
                            Login = "Poland",
                            Password = "$2a$11$/Fo41l/YUEU4L6iPU2m7M.ZXj8Fp571mTw/us3MIV6LDmVpLgx1gS",
                            PhoneNumber = "+78921234567",
                            Username = "Masha"
                        });
                });

            modelBuilder.Entity("VideoMessenger.Models.ChatInvitation", b =>
                {
                    b.HasOne("VideoMessenger.Models.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoMessenger.Models.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoMessenger.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("VideoMessenger.Models.ChatParticipant", b =>
                {
                    b.HasOne("VideoMessenger.Models.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoMessenger.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoMessenger.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VideoMessenger.Models.FriendInvitation", b =>
                {
                    b.HasOne("VideoMessenger.Models.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoMessenger.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("VideoMessenger.Models.Friends", b =>
                {
                    b.HasOne("VideoMessenger.Models.User", "Friend")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoMessenger.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VideoMessenger.Models.Message", b =>
                {
                    b.HasOne("VideoMessenger.Models.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoMessenger.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });
#pragma warning restore 612, 618
        }
    }
}
